### ISSUE TITLE
How to make co-occurrence network inference?

### ISSUE THREAD

**Issue by JiaLonghao1997** [GRONINGEN-MICROBIOME-CENTRE/Groningen-Microbiome#11]
Nice to meet you, Lianmin Chen.

I am a student in Fudan University and new to microbiological network inference. I have read the paper [Gut microbial co-abundance networks show specificity in inflammatory bowel disease and obesity](https://www.nature.com/articles/s41467-020-17840-y) carefully.  I still couldn't understand the paragraph:

Co-occurrence network inference: presence and absence of each bacterial species and metabolic pathway were treated as binary traits. The pair-wise co-occurrence relationship between two microbial factors (species or pathway) in each cohort was assessed using Pearson’s chi-squared test. If the number of co-occurrence pairs was greater than the number of co-exclusion pairs, the two microbial factors were considered to be a co-occurrence. If the number of co-occurrence pairs was less than the number co-exclusion pairs, the two factors were considered to be a co-exclusion. Permutation (100×) was conducted to determine significance at an FDR < 0.05. In each permutation, the presence and absence of each microbial factor was randomly shuffled across samples. 

And this section is not explained enough in the [code](https://github.com/GRONINGEN-MICROBIOME-CENTRE/Groningen-Microbiome/blob/0a484ad8ac1e39f2e07fe2763a1e70971de64819/Projects/Microbial%20co-abundance%20network/co-abundance%20network%20main%20codes.R).  Could you provide more information or some example? Thank you very much!

My questions were that:
(1)How do you integrate the results of  SparCC  and SpiecEasi ? Take the intersection directly?
(2)How to define and calculate co-occurrence pairs and co-exclusion pairs?
(3)There are many network inference strategies. [Bin Ma et al. Microbiome(2020)](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-020-00857-2) and [Gipsi Lima-Mendez et al. Sicence(2015) ](https://science.sciencemag.org/content/348/6237/1262073)
adopt another kind of microbiological network inference strategy.  What kind of network inference is better?

My e-mail is 19110850010@fudan.edu.cn.  If it's convenient for you, we can talk about the question more. Thank you.

Best wishes to you.

Longhao Jia

**Comment by LianminChen** [comment]
Hi Longhao,

Thanks for your interest in our work. 

(1)How do you integrate the results of SparCC and SpiecEasi ? Take the intersection directly?
R: SparCC and SpiecEasi were only for co-abundance. If a co-abundance significant in SparCC (FDR<0.05) and also present in SpiecEasi with the same direction (interaction score >0, keep in mind graphical model-based SpiecEasi cannot calculate P-value for co-abundance), then this co-abundance will be kept otherwise kick it out in the integrated co-abundance network (please check our rebuttal letter: https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-17840-y/MediaObjects/41467_2020_17840_MOESM2_ESM.pdf).

(2)How to define and calculate co-occurrence pairs and co-exclusion pairs?
R: Regarding co-occurrence network inference, basically you have two species (sp1 and sp2) and you can contract 2x2 matrix to further calculate the odds ratio (I used a plus 0.5 approach based on Valenzuela C. 1993, Rev. Med. Chil., PMID: 8085071). negative odds ratio represents co-exclusion (i.e., If the number of co-occurrence pairs was greater than the number of co-exclusion pairs, the two microbial factors were considered to be a co-occurrence. If the number of co-occurrence pairs was less than the number of co-exclusion pairs, the two factors were considered to be a co-exclusion.)

(3)There are many network inference strategies. Bin Ma et al. Microbiome(2020) and Gipsi Lima-Mendez et al. Sicence(2015) 
adopt another kind of microbiological network inference strategy. What kind of network inference is better?
R: Interesting question, for co-occurrence/exclusion basically you want to know whether two microbes always occur/disappear at the same time. So basically if your sampling is representative and MGS read depth is enough. You can just use odds ratio. Different methods have their hypothesis and the question is what is the problem with your data and what should be the suitable method theoretically? For co-abundance, it's another question i.e., the natural shape of relative abundance. You can check this paper: PMID: 26905627 


Cheers.

Lianmin
